site_name: Chromatopy Documentation
repo_url: https://github.com/FAIRChemistry/chromatopy
repo_name: FAIRChemistry/chromatopy
site_url: https://FAIRChemistry.github.io/chromatopy/
site_author: Max Häußler

nav:
  - Home: index.md
  - Data Preparation: supported_formats.md
  - Usage:
    - Read Data: examples/read_data.md
    - Define Molecules: examples/define_molecules.md
    - Define Proteins: examples/define_proteins.md
    - Visualize Data: examples/visualize.md
    - Assign Peaks: examples/peak_assignment.md
  - Installation: installation.md
  - API Reference:
    - ChromAnalyzer: api_reference/analyzer.md

plugins:
  - plotly
  - mkdocstrings
  - search


theme:
  name: material
  logo: pics/logo.png
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.indexes
    - navigation.footer
    - content.action.view
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.tabs.links
    - content.code.select
    - content.code.copy
    - content.code.annotation
    - content.tooltips
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/mhchem.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
