[tool.poetry]
name = "chromatopy"
version = "0.1.9"
description = "Tool for processing chromatography data"
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "chromatopy"}]


[tool.poetry.dependencies]
python = "^3.10"
sdRDM = { git = "https://github.com/JR-1991/software-driven-rdm.git"}
plotly = "^5.19.0"
rainbow-api = "^1.0.6"
hplc-py = "0.2.5"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.5.12"
ruff = "^0.3.0"
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.pytest.ini_options]
markers = [
    "readers: marks tests as slow (deselect with '-m \"not slow\"')",
    "core: marks tests as core (deselect with '-m \"not core\"')",
]