"""Type stubs for dotted-dict (no upstream py.typed / stubs on PyPI)."""

from typing import Any

class DottedDict(dict[str, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self) -> DottedDict: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class PreserveKeysDottedDict(dict[str, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self) -> PreserveKeysDottedDict: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
