name: Test Action

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sdRDM library
        uses: ./new_generation_test.yaml
        with:
          library_name: "chromatopy"
          # schema_path: "./.github/workflows/model.md"
          push: "false"
